[package]
name = "abc_swap"
version = "0.1.0"
authors = ["kou12345 <hi.0412.ko.2002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.3.6"
